from ConfigEngine.Generators import engine
from ConfigEngine import toBool,writeLines

@engine.assertConfig("network",(
        "hostapd_enable",
        "hostapd_interface",
        "hostapd_channel",
        "hostapd_ssid",
        "hostapd_wpa",
        "hostapd_psk"
        ))
@engine.generator("hostapd configuration")
def hostapd(io):
    io.write("# This file is auto generated by a script\n")

    # get the hostapd settings.
    network = engine.getSection("network",predicate=lambda k:k.startswith("hostapd_"))
     
    # the first thing we write to the hostapd config is the details on interface and specific
    # details. 
    if toBool(network["hostapd_enable"]) == False:
       return
    writeLines(io, [
        "interface={0}".format(network['hostapd_interface']),
        "hw_mode=g",
        "channel={0}".format(network['hostapd_channel']),
        "ssid={0}".format(network["hostapd_ssid"]),
        ])
    if( toBool( network["hostapd_wpa"]) ):
        # Enable WPA encryption
        writeLines(io, [
            "auth_algs=1",
            "wpa=2",
            "wpa_key_mgmt=WPA-PSK",
            "wpa_pairwise=CCMP",
            "rsn_pairwise=CCMP",
            "wpa_passphrase={0}".format(network["hostapd_psk"])
            ])
    # end hostapd configuration generator
